name: Provision secrets

on: 
  # push:
  #     branches:
  #     - main
  #     - feature/*
  workflow_dispatch: 

jobs:

  # If you need additional Integration Services environments, make a copy of the code block below and update at least the environmentName and integrationName for each environment.
  create_secrets_Dev:
    if: always() && !cancelled() && !failure()
    name: Development
    uses: ./.github/workflows/secret.yml
    concurrency: 'deploy'
    permissions:
      id-token: write
      contents: read
      checks: write
    with:
      runs_on: github-hosted-azure # This is the name of the self-hosted runner label
      environment: 'dev'
      keyvault_name_shared: 'kv-ae-ais-dev-nnpbak'
    secrets: inherit

 