name: Release - Sample Integration

on:
  push:
      branches:
      - main
      - feature/*

env: 
  integration_name: sample-integration
  integration_name_folder: sample-integration

jobs:
  changes:
    name: 'Detect code changes'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
      function: ${{ steps.filter.outputs.functionapp }}
      logicapp: ${{ steps.filter.outputs.logicapp }}
      github: ${{ steps.filter.outputs.github }}
      integration_name: ${{ steps.integration.outputs.integration_name }}
      integration_name_folder: ${{ steps.integration.outputs.integration_name_folder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check for changes in paths src/${{env.integration_name_folder}}/x
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            infrastructure: 
              - 'src/${{env.integration_name_folder}}/infrastructure/**'
            functionapp:
              - 'src/${{env.integration_name_folder}}/function/**'
            logicapp:
              - 'src/${{env.integration_name_folder}}/workflow/**'
            github:
              - '.github/**'
      
      - name: Set integration name outputs
        id: integration
        run: | 
          echo 'integration_name=${{env.integration_name}}' >> $GITHUB_OUTPUT
          echo 'integration_name_folder=${{env.integration_name_folder}}' >> $GITHUB_OUTPUT
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    concurrency: 'build'
    needs:
      - changes
    permissions: 
      id-token: write
      contents: read
      checks: write    
    with:
      integration_name: ${{ needs.changes.outputs.integration_name }}
      integration_name_folder: ${{ needs.changes.outputs.integration_name_folder }}
      run_tests: false
      build_infra: ${{ needs.changes.outputs.infrastructure == 'true' }}
      build_func: ${{ needs.changes.outputs.function == 'true' }}
      build_logic: ${{ needs.changes.outputs.logic == 'true' }}
      update_tools:  ${{ needs.changes.outputs.github == 'true' }}
    secrets: inherit

  # If you need additional Integration Services environments, make a copy of the code block below and update at least the environmentName and integrationName for each environment.
  deploy_Dev:
    if: always() && !cancelled() && !failure() && needs.changes.outputs.infrastructure == 'true' || needs.changes.outputs.functionapp == 'true' || needs.changes.outputs.logicapp == 'true'
    name: Development
    uses: ./.github/workflows/deploy.yml
    concurrency: 'deploy'
    needs:
      - build
    permissions:
      id-token: write
      contents: read
      checks: write
    with:
      runs_on: Dev-AIS # This is the name of the self-hosted runner label
      environment: 'dev'
      subscriptionId: '43a0a102-f88d-4e99-9987-0ead14a0f6d1'
      resourcegroup: 'AUE-DEV-ARG-Appservice'
      integration_name: ${{ needs.changes.outputs.integration_name }}
      integration_name_folder: ${{ needs.changes.outputs.integration_name_folder }}
      dotnet_version: '8.0.x'
      run_tests: true 
      functionapp_artifact_name: functionapp
      azure_functionapp_name_fmt: 'aue-{0}-func-sample-integration'
      slot: 'production'
      logicapp_artifact_name: logicapp
      azure_logicapp_name_fmt: 'aue-{0}-logic-sample-integration'
      infrastructure_artifact_name: infrastructure
      update_infra: ${{ needs.changes.outputs.infrastructure == 'true'}}
      update_func: ${{ needs.changes.outputs.functionapp == 'true'}}
      update_logic: ${{ needs.changes.outputs.logicapp == 'true'}}
    secrets: inherit

  deploy_Tst:
    if: always() && !cancelled() && !failure() && needs.changes.outputs.infrastructure == 'true' || needs.changes.outputs.functionapp == 'true' || needs.changes.outputs.logicapp == 'true'
    name: Test
    uses: ./.github/workflows/deploy.yml
    concurrency: 'deploy'
    needs:
      - deploy_Dev
    permissions:
      id-token: write
      contents: read
    with:
      runs_on: Tst-AIS # This is the name of the self-hosted runner label
      environment: 'test'
      subscriptionId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
      resourcegroup: 'AUE-TST-ARG-Appservice'
      integration_name: 'sample-integration' # Cannot use env in caller workflows so this must be a string
      integration_name_folder: 'sample-integration-ID0001' # Cannot use env in caller workflows so this must be a string
      dotnet_version: '8.0.x'
      run_tests: true 
      functionapp_artifact_name: functionapp
      azure_functionapp_name_fmt: 'aue-{0}-func-sample-integration'
      slot: 'production'
      logicapp_artifact_name: logicapp
      azure_logicapp_name_fmt: 'aue-{0}-logic-sample-integration'
      infrastructure_artifact_name: infrastructure
      update_infra: ${{ needs.changes.outputs.infrastructure == 'true'}}
      update_func: ${{ needs.changes.outputs.functionapp == 'true'}}
      update_logic: ${{ needs.changes.outputs.logicapp == 'true'}}
    secrets: inherit

  deploy_PRO:
    if: always() && !cancelled() && !failure() && needs.changes.outputs.infrastructure == 'true' || needs.changes.outputs.functionapp == 'true' || needs.changes.outputs.logicapp == 'true'
    name: Production
    uses: ./.github/workflows/deploy.yml
    concurrency: 'deploy'
    needs:
      - deploy_Tst
    permissions:
      id-token: write
      contents: read
    with:
      runs_on: PRO-AIS # This is the name of the self-hosted runner label
      environment: 'production'
      subscriptionId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
      resourcegroup: 'AUE-PRO-ARG-Appservice'
      integration_name: 'sample-integration' # Cannot use env in caller workflows so this must be a string
      integration_name_folder: 'sample-integration-ID0001' # Cannot use env in caller workflows so this must be a string
      dotnet_version: '8.0.x'
      run_tests: true 
      functionapp_artifact_name: functionapp
      azure_functionapp_name_fmt: 'aue-{0}-func-sample-integration'
      slot: 'production'
      logicapp_artifact_name: logicapp
      azure_logicapp_name_fmt: 'aue-{0}-logic-sample-integration'
      infrastructure_artifact_name: infrastructure
      update_infra: ${{ needs.changes.outputs.infrastructure == 'true'}}
      update_func: ${{ needs.changes.outputs.functionapp == 'true'}}
      update_logic: ${{ needs.changes.outputs.logicapp == 'true'}}