name: Create secrets

on:
  workflow_call:
    
    inputs:
      runs_on:
        description: Platform to execute on
        type: string
        required: true
      environment:
        description: The environment name
        required: true
        type: string
      keyvault_name_shared:  
        description: Name of the key vault to use for shared secrets
        type: string
        default: kv-ae-ais-dev-nnpbak 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Create secrets in Shared Key Vault
    runs-on: 
      group: ${{ inputs.runs_on }}
    environment: ${{inputs.environment}}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Run Pre-deployment Sript for SAP ECC Integration
        uses: azure/powershell@v2
        with:
          inlineScript: src/ecc-pricing/scripts/pre-deploy.ps1 -environmentName ${{ inputs.environment }} -keyVaultName ${{ inputs.keyvault_name_shared }} -usernameSapEcc ${{ secrets.USERNAME_SAPECC }} -userpwdSapEcc '${{ secrets.USERPWD_SAPECC }}'
          azPSVersion: "latest"

      - name: Run Pre-deployment Sript for Bunnings sales out Integration
        uses: azure/powershell@v2
        with:
          inlineScript: src/bunnings-salesout/scripts/pre-deploy.ps1 -environmentName ${{ inputs.environment }} -keyVaultName ${{ inputs.keyvault_name_shared }} -usernameSftpFileServer ${{ secrets.SFTP_USERNAME_SI_SERVER }} -userpwdSftpFileServer '${{ secrets.SFTP_USERPWD_SI_SERVER }}' -usernameSapBwSserver ${{ secrets.USERNAME_SAPBW_FILESHARE }} -userpwdSapBwSserver '${{ secrets.USERPWD_SAPBW_FILESHARE }}'
          azPSVersion: "latest"

      